### ISSUE TITLE
Is this possible? Scan dic file and obtain all forms of all files

### ISSUE THREAD

**Issue by MonsterMMORPG** [karandesai28/NHunspell-Implementation-in-Console-Application-with-custom-dictionary#1]
What i want is simple

I would like to obtain all words that can be composed from the given word

E.g.

make/UAGS

in us.dic file

So i want to obtain all words that can be obtained from this word/suffix combination

e.g. results are : made, making, makes etc

**Comment by karandesai28** [comment]
Hi @MonsterMMORPG , sorry for replying so late. I, actually created this basic project to understand working of Nhunspell and spell-checking mechanism better. I have not dug deeper though. However, you can surely post this question on official Nhunspell github [repository ](https://github.com/hunspell/hunspell/issues) or can refer [this ](https://stackoverflow.com/questions/25614279/hunspell-affix-condition-regex-format-any-way-to-match-the-start) related question on SO.

Hope it helps. Happy Coding :)
